version: '3'
services:
  mongo:
    restart: always
    image: mongo:3.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  
  explorer:
    image: ichain
    restart: always
    ports:
      - 80:8080
    environment:
       - MONGO_URI=mongodb://mongo:27017/ichain
    command: rest-server
    
  explorer:
    image: ichain
    restart: always
    ports:
      - 80:8080
    environment:
       - MONGO_URI=mongodb://mongo:27017/ichain
    command: start-indexer