
export const RECEIVE_BLOCKS = 'RECEIVE_BLOCKS'
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS'
export const RECEIVE_ADDRESSES = 'RECEIVE_ADDRESSES'
export const RECEIVE_ASSETS = 'RECEIVE_ASSETS'